const hostUrl = process.env.NEXT_PUBLIC_API
export const registerUserUrl = `${hostUrl}/register/candidate/`
export const loginUserUrl = `${hostUrl}/login/candidate/`
export const getUserUrl = `${hostUrl}/users/me/`
export const userCertificates = `${hostUrl}/candidate/certificates/`
export const userSkills = `${hostUrl}/candidate/skills/`
export const userCv = `${hostUrl}/candidate/resume/`
export const changePassword = `${hostUrl}/password/change/`
export const userJobDetails = `${hostUrl}/candidate/job-detail/`
export const registerEmployerUrl = `${hostUrl}/register/employer/`
export const loginEmployerUrl = `${hostUrl}/login/employer/`
export const empCompanyInformation = `${hostUrl}/organization/`